name: Bye Net Relay
on: [workflow_dispatch]
jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gost
        run: |
          wget https://github.com/ginuerzh/gost/releases/download/v2.11.1/gost-linux-amd64-2.11.1.gz
          gunzip gost-linux-amd64-2.11.1.gz
          mv gost-linux-amd64-2.11.1 gost
          chmod +x gost
          
      - name: Open Net Valve
        run: |
          echo "🚀 Master Bye! ท่อเน็ตเปิดแล้ว"
          ./gost -L=ss://aes-256-gcm:MasterBye123@:8080
