name: System Optimizer
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to relay'
        required: true
        default: 'google.com:443'
jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Open Net Valve
        run: |
          wget https://github.com/ginuerzh/gost/releases/download/v2.11.1/gost-linux-amd64-2.11.1.gz
          gunzip gost-linux-amd64-2.11.1.gz
          chmod +x gost-linux-amd64-2.11.1
          ./gost-linux-amd64-2.11.1 -L ss://aes-256-gcm:MasterBye123@:8080 -F ${{ github.event.inputs.target }}
